title: "Azucena Jimenez - Portfolio"
email: "azucenaljim1@csu.fullerton.edu"
description: "My personal portfolio showcasing my projects and experience."
baseurl: ""  
url: "https://azjimenezmartinez.github.io"
theme: minima 
